### PR TITLE
Redirect to main wiki.

### PR DESCRIPTION
**Pull request by Daniel4-Scratch**

### CODE REVIEW

**Comment by Daniel4-Scratch** [comment]
😕

**Comment by GrahamSH-LLK** [comment]
I think we're going to use this site for actual stuff, so I'm going to close this.

**Comment by Daniel4-Scratch** [comment]
Ok, like the news or blog page?

**Comment by GrahamSH-LLK** [comment]
Yeah!

**Comment by Daniel4-Scratch** [comment]
Ok, I gotcha

**Pull request closed without merging**
